"""creating database

Revision ID: 565231082c05
Revises:
Create Date: 2024-09-12 16:15:05.188408

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '565231082c05'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
