"""empty message

Revision ID: c2c4bfe08ee3
Revises: df4db0a3a8e5
Create Date: 2024-09-12 22:01:39.660906

"""
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = 'c2c4bfe08ee3'
down_revision: Union[str, None] = 'df4db0a3a8e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
