"""creating database

Revision ID: f99d8f06f041
Revises: 565231082c05
Create Date: 2024-09-12 16:15:44.167787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData, Table

# revision identifiers, used by Alembic.
revision: str = 'f99d8f06f041'
down_revision: Union[str, None] = '565231082c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
