name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: install poetry
        run: pip install poetry
      - name: poetry init
        run: poetry install
      - name: flake8 Lint
        run: poetry run flake8 --config ./.configure/flake8
      - name: Hello world action step
        id: hello
        uses: actions/postgres@15-alpine
        with:
          POSTGRES_DB: "test_db"
          POSTGRES_USER: "test_db"
          POSTGRES_PASSWORD: "test_db"
      - name: run pytest
        run: poetry run pytest src/test
